// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: token/issuer/service.proto

package issuerconnect

import (
	issuer "buf.build/gen/go/authaas/token-issuer-service/protocolbuffers/go/token/issuer"
	connect "connectrpc.com/connect/v2"
	context "context"
	sync "sync"
)

const (
	// ServiceName is the fully-qualified name of the Service service.
	ServiceName = "token.issuer.Service"
)

// These constants are the procedure names of the RPCs defined in this package. They're exposed at
// runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ServiceIssueProcedure is the procedure name of the Service's Issue RPC.
	ServiceIssueProcedure = "/token.issuer.Service/Issue"
)

var (
	serviceIssueSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     issuer.File_token_issuer_service_proto.Services().ByName("Service").Methods().ByName("Issue"),
			Procedure:  ServiceIssueProcedure,
		}
	})
)

// ServiceClient is a client for the token.issuer.Service service.
type ServiceClient interface {
	// Mints a signed token for the principal the proof names, consuming the
	// grant it carries. Refuses when the grant is not the outstanding one.
	Issue(context.Context, *issuer.IssueRequest) (*issuer.IssueResponse, error)
}

// NewServiceClient constructs a client for the token.issuer.Service service. Multiple service
// clients may share a single connect.Client.
func NewServiceClient(client *connect.Client) ServiceClient {
	return &serviceClient{client: client}
}

// ServiceHandler is an implementation of the token.issuer.Service service.
type ServiceHandler interface {
	// Mints a signed token for the principal the proof names, consuming the
	// grant it carries. Refuses when the grant is not the outstanding one.
	Issue(context.Context, *issuer.IssueRequest) (*issuer.IssueResponse, error)
}

// RegisterServiceHandler registers svc as the token.issuer.Service implementation on server.
func RegisterServiceHandler(server *connect.Server, svc ServiceHandler) {
	adapter := serviceHandler{svc: svc}
	server.Register(
		connect.Method{Spec: serviceIssueSpec(), Handler: adapter.issue},
	)
}

// UnimplementedServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedServiceHandler struct{}

func (UnimplementedServiceHandler) Issue(context.Context, *issuer.IssueRequest) (*issuer.IssueResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "token.issuer.Service.Issue is not implemented")
}

type serviceClient struct {
	client *connect.Client
}

func (c *serviceClient) Issue(ctx context.Context, req *issuer.IssueRequest) (*issuer.IssueResponse, error) {
	var res issuer.IssueResponse
	if err := c.client.CallUnary(ctx, serviceIssueSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

type serviceHandler struct{ svc ServiceHandler }

func (h serviceHandler) issue(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req issuer.IssueRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.Issue(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}
